version: '3'

services: 
    db:
        image: mysql:5.7.28
        ports: 
            - '3306:3306'
        environment: 
            - MYSQL_ROOT_PASSWORD=some_password
        restart: unless-stopped
        
    backend:
        image: davidcarl/si-mp3-backend
        ports:
            - '88:3001'
        links:
            - db
        depends_on:
            - db
        restart: unless-stopped
        
    frontend:
        image: davidcarl/si-mp3-frontend
        ports:
            - '80:3000'
        links:
            - backend
        depends_on:
            - backend
        restart: unless-stopped