version: 2
jobs:
  build:
    # working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76

      - run: 
          name: Docker build Backend
          command: |
            ls -all && cd backend && docker build -t backend .

      - run: 
          name: Docker build Backend
          command: |
            ls -all && cd frontend && docker build -t frontend .